# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1f9b664be285b2b9fdd730297d0ad4550fd1811a1ba7b0751f0811aa97a0968c1c9b3ba388453bb39949d84a77959b5a9a30168dfe23931d69c43075503300f

test:
  secret_key_base: e6adc048b24d6c2e83d3efde38355bca4a3bf7479ccac491e1e8a94861f09deaacb29fec27d689f8d6572804fc1e791af70e430bde7ee60bb885ef176f1cbd9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
